src/components/ProgramRecord/ProgramRecord.jsx, src/components/ProgramRecord/ProgramRecordActions.jsx, src/components/ProgramRecord/data/service.js, src/components/ProgramRecord/test/CopyToClipboard.test.jsx, src/components/ProgramRecord/test/DownloadCsv.test.jsx, src/components/ProgramRecord/test/ProgramRecord.test.jsx, src/components/ProgramRecordAlert/ProgramRecordAlert.jsx, src/components/ProgramRecordAlert/test/__factories__/programRecordAlert.factory.js, src/components/ProgramRecordSendModal/SendLearnerRecordModal.jsx, src/components/ProgramRecordSendModal/data/service.js, src/components/ProgramRecordSendModal/test/SendLearnerRecordModal.test.jsx, src/index.jsx
This PR adds three analytics events to the program details page. These events are carried over from the legacy frontend in [Credentials](https://github.com/openedx/credentials/tree/master/credentials/static/components).
The events added in this PR:
1. Opening the modal for sending program records - `edx.bi.credentials.program_record.send_started`
2. When the program records are sent for credit - `edx.bi.credentials.program_record.send_finished`
3. When the URL for the public record is copied - `edx.bi.credentials.program_record.share_url_copied`
_Minor change: modified the name of a prop from 'uuid' to 'programId' in an attempt to make things more clear_
=> feat: added analytics events

src/components/ProgramRecord/ProgramRecord.jsx, src/components/ProgramRecord/ProgramRecordActions.jsx, src/components/ProgramRecord/test/CopyToClipboard.test.jsx, src/components/ProgramRecord/test/ProgramRecord.test.jsx, src/components/ProgramRecord/test/__factories__/programRecord.factory.js
This PR addresses a change from the MFE conversion. In this conversion, we've decided to remove the modal that opens up when a user wants to copy a public link. In its place is a button that conditionally renders based on the existence of a public record. In order to accommodate this change, we had to address a few things [outlined here](https://2u-internal.atlassian.net/jira/software/c/projects/APER/boards/585?modal=detail&selectedIssue=APER-1947), namely:
- What information is rendered to the page for each instance
- How do we re-implement the analytics event that would fire when the modal opened up
The initial REST API call that retrieves program details also contains a field for the `shared_program_record_uuid` which will be populated if a public record already exists. In this …
=> feat: create/copy public record button

src/components/ProgramRecord/ProgramRecordActions.jsx
[APER-1975]
We're just going to generate links to the Credentials IDA and we will let the IDA figure out where the user should be directed to (either the LR MFE or the legacy frontend). This makes handlings URLs much easier if we just let the backend manage this work.
=> fix: don't generate frontend specific urls for the Learner Record MFE

README.rst, src/components/ProgramRecord/ProgramRecordActions.jsx
[APER-1975]
This change backports recent changes to the Learner Record MFE supporting the Credentials IDA and the Support Tools MFE. The following changes have been cherry picked from the main branch:
- chore: add some additonal docs for environment flags (cherry picked from commit c1fda7f6acffd9e644272261d3252f39832c192f)
- fix: don't generate frontend specific urls for the Learner Record MFE (cherry picked from commit f8898567f202207fa707cd2458985e31301361ac)
=> chore: backport learner record redirection changes to Olive

src/components/ProgramRecord/data/service.js
This is to fix a bug where learners are unable to create and copy a program record link. See [APER-2224](https://2u-internal.atlassian.net/browse/APER-2224) for more details.
=> fix: create program link

src/components/ProgramRecord/data/service.js
[Second attempt]
This is to fix a bug where learners are unable to create and copy a program record link. See [APER-2224](https://2u-internal.atlassian.net/browse/APER-2224) for more details.
=> fix: create program link v2

src/components/ProgramCertificateModal/messages.js
The PR fixes Verifiable Credentials feature bug.
There is a modal window with step-by-step instructions (see Figma design screenshot). Those steps were shuffled.
=> fix: [FC-0006] verifiable credentials QR code modal instructions

src/index.jsx
Description:
Resolves the bug APER-2606: [Learner unable to create public record without reauthenticating](https://2u-internal.atlassian.net/browse/APER-2603)
When the learner attempted to create a public record link, their clipboard copied the private URL and they weren't able to create a public URL unless they re-authenticated. This PR wraps the `ProgramRecordsList`, `ProgramCertificatesList`, and the private version of `ProgramRecord` with `AuthenticatedPageRoute`, which allows for the user to experience a redirect "to the login page when the route becomes active and the user is not authenticated" [source](https://openedx.github.io/frontend-platform/module-React.html#.AuthenticatedPageRoute). 
Note that the public view of `ProgramRecord` is not wrapped in the `AuthenticatedPageRoute`. …
=> fix: add authenticatedpageroute so learner can create a shared record link

.env.development, README.rst, src/components/ProgramRecordsList/ProgramRecordsList.jsx, src/index.jsx
[APER-2922]
This PR removes the `USE_LR_MFE` feature flag. This feature flag was initially added to redirect learners back to the legacy frontend in Credentials when viewing a Program Record. This was so we could release the Learner Record MFE in phases while we were implementing the design.
Now that the legacy frontend has been removed from Credentials, this functionality and feature flag is no longer needed.
=> feat!: Remove unused feature flag

module.config.js.example, src/components/ProgramRecord/ProgramRecord.scss
[APER-2969]
This PR removes a piece of custom CSS we wrote to invert colors of icons under certain circumstances. This was originally added to resolve a problem with Paragon that has since been resolved (and is now the source of the icon color problem).
Problem today on Stage (with edX.org branding):
After changes (with edX.org branding):
After changes (with Open edX branding):
=> fix: fix icon color

README.rst
GitHub could not render the README file because of issues with titles. We take the opportunity to solve a few additional issues.
=> docs: fix README rendering and various issues

Makefile, package-lock.json, package.json
Similar to https://github.com/openedx/frontend-app-communications/pull/187.
- install atlas
- remove `--filter` to pull all languages by default
- use ATLAS_OPTIONS to allow custom `--filter`
- include frontend-platform in `atlas pull`
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
=> feat: tutor-mfe compatiblilty for atlas pull | FC-0012

patches/@edx+frontend-build+13.0.14.patch
[APER-2786](https://2u-internal.atlassian.net/browse/APER-2786)
This is a follow-up to #275 to have Webpack Prod config use `env.config.js` for assigning `NEW_RELIC_APP_ID` and `BASE_URL` during the creation of two New Relic plugins. 
This work is a temporary patch until we can add these changes to `frontend-build` and Learner Record migrates from using `@edx/frontend-build` to `@openedx/frontend-build` as a dependency. 
Closes #281
=> fix: add env config handling in patch of webpack prod config

patches/@edx+frontend-build+13.0.14.patch
A temporary PR to determine the absolute path of Learner Record when being built by GoCD.
=> temp: add a console log in webpack prod to determine the absolute path in a GoCD build

patches/@edx+frontend-build+13.0.14.patch
[APER-2786](https://2u-internal.atlassian.net/browse/APER-2786)
This PR was part of investigative work to enable JS configs in Production. 
Removes the console.log from #284
=> refactor: remove console log in webpack patch

src/components/ProgramCertificatesList/ProgramCertificatesList.jsx, src/components/ProgramRecordsList/ProgramRecordsList.jsx
Our proposal is to add `<div class="container-fluid">` inside the `<main id="main-content">` block. This will allow limiting the maximum width of the content when necessary. Otherwise, the content will span the entire width of the page, as it would without this div.
Also classes `pl-4` and `pr-4` were removed from main-content, because `container-fluid` already has left and right paddings
Example screenshot width content max-width
=> feat: Add a fluid container to allow for limiting the maximum width of the content

src/components/ProgramCertificatesList/ProgramCertificatesList.jsx, src/components/ProgramRecordsList/ProgramRecordsList.jsx
This is backport from master https://github.com/openedx/frontend-app-learner-record/pull/276
Our proposal is to add `<div class="container-fluid">` inside the `<main id="main-content">` block. This will allow limiting the maximum width of the content when necessary. Otherwise, the content will span the entire width of the page, as it would without this div.
Also classes `pl-4` and `pr-4` were removed from main-content, because `container-fluid` already has left and right paddings
Example screenshot width content max-width
=> feat: Add a fluid container to allow for limiting the maximum width of the content [backport from master]

src/components/ProgramRecord/ProgramRecord.jsx, src/components/ProgramRecordsList/ProgramRecordsList.jsx, src/utils.js, src/utils.test.js
Internal routes don't respect the PUBLIC_PATH which leads to redirecting to incorrect URLs.
Add a new util function for constructing the correct internal route URL.
You'll need an instance deployed with the common domain for MFEs (each MFE should have the PUBLIC_PATH set).
You can reproduce it using Tutor.
**Devstack uses separate domains for each MFE so you won't reproduce the issue there!**
1. Set up a program
2. Go to Profile and click on "View My Records" button 
3. Click on "View Program Record" button 
PUBLIC_PATH for Learner Record MFE is ignored, and the user is redirected to the wrong URL 
The same result on the Program Records page for the "Back To My Records" link 
Correct internal routing is performed
I'll create a backport PR for Quince soon
=> fix: internal routing ignores public path

src/components/ProgramRecord/ProgramRecord.jsx, src/components/ProgramRecordsList/ProgramRecordsList.jsx, src/utils.js, src/utils.test.js
The only difference is that the quince version uses an older version of the frontend-platform and there is no `getPath` function there. The behavior is the same.
Internal routes don't respect the PUBLIC_PATH which leads to redirecting to incorrect URLs.
Add a new util function for constructing the correct internal route URL.
You'll need an instance deployed with the common domain for MFEs (each MFE should have the PUBLIC_PATH set).
You can reproduce it using Tutor.
**Devstack uses separate domains for each MFE so you won't reproduce the issue there!**
1. Set up a program
2. Go to Profile and click on "View My Records" button 
3. Click on "View Program Record" button 
PUBLIC_PATH for Learner Record MFE is ignored, and the user is redirected to the wrong URL 
The same result on the Program …
=> [BACKPORT] fix: internal routing ignores public path

package.json
This reverts commit https://github.com/openedx/frontend-app-learner-record/commit/38e0f7abe5a1790fbbb04f5e79338ebc0a53a0c5. This version of testing-library/react doesn't play well with our current version of React.
We shouldn't upgrade this library until we're running a newer version of React in this MFE.
=> revert: "chore(deps): update dependency @testing-library/react to v14"

.github/workflows/CODEOWNERS
This PR adds the 2U-Aperture team as code owners of Learner Record MFE. This will allow us more visibility on PRs from contributors outside of the team and visibility for those contributors to request a code review from our team. 
APER-3261
=> chore: add codeowners files to .github workflow

package-lock.json, package.json
Upgrade to Paragon v22. The breaking changes are for components that are not used by this MFE (see [release notes](https://github.com/openedx/paragon/releases/tag/v22.0.0))
=> chore(deps): upgrade paragon v22

.github/workflows/ci.yml, .github/workflows/lockfileversion-check.yml
Complete the upgrade to Node 20 by removing the Node 18 CI check and going back to using `.nvmrc` as the source of truth for which version to use.
See [the tracking issue](https://github.com/openedx/frontend-app-learner-record/issues/298) for futher information.
=> test: Remove support for Node 18

src/components/ProgramRecord/ProgramRecordActions.jsx, src/components/ProgramRecord/test/DownloadCsv.test.jsx
Adds user-facing errors if errors appear on download or creation of shared program record.
FIXES: APER-3170
=> feat: informative errors on failure to download or create shared record

src/components/ProgramRecordsList/ProgramRecordsList.jsx
This PR adds the hyperlink icon to the statement that redirects to the record's help page.
https://github.com/openedx/frontend-app-learner-record/issues/456
=> fix: remove showLaunchIcon from Hyperlink component

src/components/ProgramCertificatesList/ProgramCertificatesList.jsx, src/components/ProgramRecordsList/ProgramRecordsList.jsx
now that the legacy profile and account pages have been removed, we need to make sure that all of the links point to the MFE URLs; we were relying on the legacy applications to do redirection before.
FIXES: APER-3884
FIXES: openedx/public-engineering#71
=> chore: make sure links point to MFE not legacy

src/components/ProgramRecord/ProgramRecord.jsx, src/components/ProgramRecord/RecordsHelp.jsx, src/components/ProgramRecordSendModal/SendLearnerRecordModal.scss, src/components/ProgramRecordsList/ProgramRecordsList.jsx
**Minor fix for Back to My Records button**
**First proposal:** make the button look the same as the button on the records page
**Second proposal:** remove the `<a>` tag from the `<button>` tag. The current approach is not recommended due to potential accessibility and semantic issues
**Decrease font size for the `Questions about Learner Records` title - to match with the same title on Records page**
**Send Program Record modal window - checkboxes alignment**
Before
After
=> feat: UI improvements

package-lock.json, package.json, src/components/NavigationBar/test/NavigationBar.test.jsx
This PR updates the `frontend-platform` dependency to `^8.3.1`, and fixes a few tests the broke in the process.
The following tests were failing (see https://github.com/openedx/frontend-app-learner-record/actions/runs/13758418634/job/38469530685)
*  navigation-bar › renders the component with enabled the Verifiable Credentials functionality
* Made it `async`
* Switched from `expect`/`getByText`/`toBeTruthy` to [`findByText`](https://testing-library.com/docs/dom-testing-library/api-async/#findby-queries)
*  navigation-bar › redirects the appropriate route on tab click
* Made it `async`
* Added an `await screen.findByText` after render to ensure we have something to click
=> fix(deps): update `frontend-platform` to `^8.3.1`

package-lock.json
Somehow a rebase led to https://github.com/openedx/frontend-app-learner-record/pull/509 showing CI passing despite a `package-lock` inconsistency, leading the `npm ci` not matching when it landed on `master`.
This PR just regenerates `package-lock.json` to resolve that.
=> chore: regenerate `package-lock.json`

src/components/Certificate/Certificate.jsx, src/components/CertificateModal/CertificateModal.jsx, src/components/CertificatesList/CertificatesList.jsx, src/components/Head/Head.jsx, src/components/NavigationBar/NavigationBar.jsx, src/components/ProgramRecord/ProgramRecordHeader.jsx, src/components/ProgramRecord/ProgramRecordTable.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Closes #568
=> Replace injectIntl with the useIntl() hook
